baseURL = "https://k8s-contributors.netlify.com/"
languageCode = "en-us"
title = "Kubernetes Contributors"
disableKinds = ["taxonomy", "taxonomyTerm"]
pygmentsCodefences = true
pygmentsStyle = "dracula"

[params]
fontAwesomeVersion = "5.8.1"
sansSerifFont = "Roboto"
twitterHandle = "kubernetes"
googleAnalyticsId = "180100527"

[params.fullcalendar]
js = ["core", "google-calendar", "list"]
css = ["core", "list"]

[[params.fonts]]
name = "Roboto"
sizes = [300,400,600,700]

[menu]
[[menu.sidebar]]
name = "Role Board"
url = "https://discuss.kubernetes.io/c/contributors/role-board"
